version: '3.9'

services:
  frontend:
    image: wjyask/blockscout-frontend:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    ports:
      - 3000:3000
    # volumes:
    #   - ./.next/standalone/.next:/app/.next
    #   - ./.next/standalone/node_modules:/app/node_modules
    #   - ./.next/standalone/pages:/app/pages
    #   - ./.next/standalone/ui:/app/ui
    #   - ./.next/standalone/package.json:/app/package.json
    #   - ./.next/standalone/server.js:/app/server.js
    #   - ./.next/static:/app/.next/static
    #   - ./.next/public:/app/public
